
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'feifei', N'采购方收货后，可操作相关对账数据', NULL, 0, NULL, N'采购方收货后，可操作相关对账数据', NULL, 0, 0, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), NULL, CAST(0x077023CBFA5FFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES ( N'admin', N'AccountStatement', N'AccountStatementList', N'新建/编辑合同为通用合同类型，至少需要两方签署方，最多十方签署方', N'', 1, NULL, N'新建/编辑合同为通用合同类型，至少需要两方签署方，最多十方签署方', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'RetutrnContract', N'页面-对账单草稿箱', N'', 1, NULL, N'页面-对账单草稿箱', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES ( NULL, N'AccountStatement', N'DraftAccountStatement', N'操作-删除\批量删除对账单草稿', N'', 1, NULL, N'操作-删除\批量删除对账单草稿', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES ( NULL, N'AccountStatement', N'Index', N'电商分为：通用合同、对账单合同、销售合同、采购合同、协议合同这5大类合同，不同业务产生不同类型的合同，通用合同可单独上传', N'', 1, NULL, N'电商分为：通用合同、对账单合同、销售合同、采购合同、协议合同这5大类合同，不同业务产生不同类型的合同，通用合同可单独上传', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'DeleteMultipleUrl', N'操作-审核合同', N'', 1, NULL, N'操作-审核合同', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES ( NULL, N'AccountStatement', N'RemoveCurrencySignService', N'新建/编辑合同为通用合同类型，至少需要两方签署方，最多十方签署方', N'', 1, NULL, N'新建/编辑合同为通用合同类型，至少需要两方签署方，最多十方签署方', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'Index', N'采购方收货后，可操作相关对账数据', N'', 1, NULL, N'采购方收货后，可操作相关对账数据', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'CurrencySignOperationLog', N'采购方收货后，可操作相关对账数据', N'', 1, NULL, N'采购方收货后，可操作相关对账数据', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'SetIsShowArticle', N'页面包含六个子页面，应募管理，报价管理，投标管理，竞价管理，报价邀请，采购收藏', N'', 1, NULL, N'页面包含六个子页面，应募管理，报价管理，投标管理，竞价管理，报价邀请，采购收藏', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'SetEnterpriseAutobiographyToDefault', N'新建/编辑合同为通用合同类型，至少需要两方签署方，最多十方签署方', N'', 1, NULL, N'新建/编辑合同为通用合同类型，至少需要两方签署方，最多十方签署方', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'QuotedPriceRecord', N'电商分为：通用合同、对账单合同、销售合同、采购合同、协议合同这5大类合同，不同业务产生不同类型的合同，通用合同可单独上传', N'', 1, NULL, N'电商分为：通用合同、对账单合同、销售合同、采购合同、协议合同这5大类合同，不同业务产生不同类型的合同，通用合同可单独上传', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'SupplierRecruitDetail', N'采购方收货后，可操作相关对账数据', N'', 1, NULL, N'采购方收货后，可操作相关对账数据', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES ( NULL, N'AccountStatement', N'SaveRecruitApply', N'采购方收货后，可操作相关对账数据', N'', 1, NULL, N'采购方收货后，可操作相关对账数据', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES ( NULL, N'AccountStatement', N'QuotedPrice', N'操作-同步合同数据', N'', 1, NULL, N'操作-同步合同数据', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES ( NULL, N'AccountStatement', N'Index', N'采购方收货后，可操作相关对账数据', N'', 1, NULL, N'采购方收货后，可操作相关对账数据', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'AccountStatementList', N'新建/编辑合同为通用合同类型，至少需要两方签署方，最多十方签署方', N'', 1, NULL, N'新建/编辑合同为通用合同类型，至少需要两方签署方，最多十方签署方', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'RetutrnContract', N'页面-对账单草稿箱', N'', 1, NULL, N'页面-对账单草稿箱', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES ( NULL, N'AccountStatement', N'DraftAccountStatement', N'操作-删除\批量删除对账单草稿', N'', 1, NULL, N'操作-删除\批量删除对账单草稿', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'Index', N'电商分为：通用合同、对账单合同、销售合同、采购合同、协议合同这5大类合同，不同业务产生不同类型的合同，通用合同可单独上传', N'', 1, NULL, N'电商分为：通用合同、对账单合同、销售合同、采购合同、协议合同这5大类合同，不同业务产生不同类型的合同，通用合同可单独上传', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES ( NULL, N'AccountStatement', N'DeleteMultipleUrl', N'操作-审核合同', N'', 1, NULL, N'操作-审核合同', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES ( NULL, N'AccountStatement', N'RemoveCurrencySignService', N'新建/编辑合同为通用合同类型，至少需要两方签署方，最多十方签署方', N'', 1, NULL, N'新建/编辑合同为通用合同类型，至少需要两方签署方，最多十方签署方', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'Index', N'采购方收货后，可操作相关对账数据', N'', 1, NULL, N'采购方收货后，可操作相关对账数据', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'CurrencySignOperationLog', N'采购方收货后，可操作相关对账数据', N'', 1, NULL, N'采购方收货后，可操作相关对账数据', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES ( NULL, N'AccountStatement', N'SetIsShowArticle', N'页面包含六个子页面，应募管理，报价管理，投标管理，竞价管理，报价邀请，采购收藏', N'', 1, NULL, N'页面包含六个子页面，应募管理，报价管理，投标管理，竞价管理，报价邀请，采购收藏', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'SetEnterpriseAutobiographyToDefault', N'新建/编辑合同为通用合同类型，至少需要两方签署方，最多十方签署方', N'', 1, NULL, N'新建/编辑合同为通用合同类型，至少需要两方签署方，最多十方签署方', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'QuotedPriceRecord', N'电商分为：通用合同、对账单合同、销售合同、采购合同、协议合同这5大类合同，不同业务产生不同类型的合同，通用合同可单独上传', N'', 1, NULL, N'电商分为：通用合同、对账单合同、销售合同、采购合同、协议合同这5大类合同，不同业务产生不同类型的合同，通用合同可单独上传', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'SupplierRecruitDetail', N'采购方收货后，可操作相关对账数据', N'', 1, NULL, N'采购方收货后，可操作相关对账数据', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'SaveRecruitApply', N'采购方收货后，可操作相关对账数据', N'', 1, NULL, N'采购方收货后，可操作相关对账数据', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'QuotedPrice', N'操作-同步合同数据', N'', 1, NULL, N'操作-同步合同数据', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'AccountStatement', N'QuotedPrice', N'操作-同步合同数据', N'', 1, NULL, N'操作-同步合同数据', NULL, 0, 1, 0, N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2), N'admin@126.com', CAST(0x07C00334B15BFE3F0B AS DateTime2))
GO
INSERT [dbo].[Permission] ([AreaName], [ControllerName], [ActionName], [Description], [Remark], [Index], [ParentId], [Name], [TreeCode], [Leaf], [Level], [IsDeleted], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate]) VALUES (NULL, N'permissions', N'roles', N'权限角色列表', NULL, 0, NULL, N'权限角色', NULL, 0, 0, 0, NULL, CAST(0x0730ABDD6888FE3F0B AS DateTime2), NULL, CAST(0x0730ABDD6888FE3F0B AS DateTime2))
GO

